  server:
    port: 8083


  Spring:
    data:
      mongodb:
        uri: mongodb://localhost:27017
        database: myMongoDB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        default-zone: http://localhost:8761/eureka
