      server:
        port: 8081

      spring:
        datasource:
          url:  jdbc:postgresql://localhost:5432/postgres
          username : postgres
          password : test1234

        jpa:
          hibernate:
            ddl-auto: update
          show-sql: true

      eureka:
        instance:
          prefer-ip-address: true
        client:
          fetch-registry: true
          register-with-eureka: true
          serverUrl:
            defaultZone: http://localhost:8761/eureka/

