  Server:
    Port: 8084

  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        default-zone: http://localhost:8761/eureka

  spring:
#    datasource:
#      url: jdbc:postgresql://localhost:5432/postgres
#      username: postgres
#      password: test1234
    application:
      name: API-GATEWAY

    cloud:
      gateway:
        routes:
          - id: USERSERVICE
            uri: lb://USERSERVICE
            predicates:
              - Path=/api/**,/**

          - id: RATINGSERVICE
            uri: lb://RATINGSERVICE
            predicates:
              - Path=/api/**

          - id: HOTELSERVICE
            uri: lb://HOTELSERVICE
            predicates:
              - Path=/api/**

#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true